### ISSUE TITLE
Tailwind plugins

### ISSUE THREAD

**Issue by danfarrowadtrak** [adtrak-core/boilerplate#11]
I've used a few TW plugins that just help a lot, some of which I think Adtrak may use.

**tailwindcss-filters**
https://github.com/benface/tailwindcss-filters

Allows usage of filters like grayscale.

**tailwindcss-gradients**
https://github.com/benface/tailwindcss-gradients

Allows customisation and creation of gradients without having to create them in separate CSS files.

**Comment by stephengreig** [comment]
I think these are useful additions. I know I've had to create new partial files before just to add a CSS filter or a gradient, so I think these are worthwhile.
