### ISSUE TITLE
"custom" CSS File

### ISSUE THREAD

**Issue by danfarrowadtrak** [adtrak-core/boilerplate#13]
Just an idea, but having an empty "custom" css file so people add their own styles into it could be good. We shouldnt need loads of partials anymore with Tailwind, so having a central file for custom things people make should be enough IMO.

In my last freelance project, I literally had 10 lines of custom CSS I couldn't achieve via Tailwind which went into this.

Just a thought on that really to avoid people creating loads of partials etc.

**Comment by tomnightingale-adtrak** [comment]
I've added a comment to main.scss and hope that people write custom css below the @import declarations.
