### ISSUE TITLE
Abstract jQuery commands into single files

### ISSUE THREAD

**Issue by ghost** [adtrak-core/boilerplate#20]
Not immediate, but convert all jQuery run items into standalone vanilla/ES6 JS in their own files, and let Gulp smash them together.

Example - `back to top` function - rewrite into JS, add to `back-to-top.js` file inside `js` folder.

**Comment by danfarrowadtrak** [comment]
The idea here is to reduce dependency on jQuery with a goal one day to remove it entirely from the boilerplate.
