### ISSUE TITLE
image-sizes.php

### ISSUE THREAD

**Issue by danfarrowadtrak** [adtrak-core/boilerplate#21]
This should be totally redundant and deletable now, as Twig will handle image sizing using resize?

**Comment by tomnightingale-adtrak** [comment]
It's probably worth leaving this in in-case we need custom sizing for images embedded within posts?

**Comment by danfarrowadtrak** [comment]
Do you mean in the WYSIWYG? Maybe - although I reckon thumbnail, medium, medium-large and large should be enough?

Up to you on that one.
