### ISSUE TITLE
Potentially rebase to be within the wp-content folder

### ISSUE THREAD

**Issue by samuelgoddard** [adtrak-core/boilerplate#28]
Not sure if feasible, but might be a little easier if the project root was within the `wp-content` folder as atm cloning into a full folder (with all of wordpresse's other shite, wp-admin etc etc) is a little bit tricky. If rebased to the `wp-content` folder you can just delete the entire `wp-content` folder of a new wordpress install and clone directly to that

**Comment by danfarrowadtrak** [comment]
The guide mentions creating a new empty repo on Gitlab, cloning that repo locally then downloading and unzipping this boilerplate into the right place. The reason to do it this way is to prevent anyone forgetting to set up their Gitlab/Github and pushing to the wrong place, i.e. to this repo. In essence, we want people *not* to clone this repo and download it as a zip instead. Keeping tabs on ~20 developers of varying skill set and experience is difficult, so adopting processes like this can really help mitigate problems.

@samuelgoddard That make sense?

**Comment by samuelgoddard** [comment]
Good point, makes sense to me! @danfarrowadtrak
