### ISSUE TITLE
WooCom: Post category/archive pages 404

### ISSUE THREAD

**Issue by stephengreig** [adtrak-core/boilerplate#89]
The category pages and yearly archive pages for the standard Posts are 404ing. Experienced on two separate WooCom builds suggesting an issue with the boilerplate.

**Comment by tomnightingale-adtrak** [comment]
Updating permalinks to the below seems to fix this issue:
![image](https://user-images.githubusercontent.com/9697691/107646049-6cf48300-6c71-11eb-8fbe-54b2b43972d3.png)
